apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: producer
        image: 717279735097.dkr.ecr.us-east-1.amazonaws.com/producer:latest
        ports:
        - containerPort: 80
        env:
        - name: KAFKA_BROKER
          value: "my-cluster-kafka-bootstrap:9092"
        - name: KAFKA_TOPIC
          value: "test-topic"
